name: Build and Deploy site
on:
  push:
    branches: main
      
jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            cd $HOME/sites/silearning-center/website
            git pull
            rm -rf .next
            export PATH="$HOME/.local/share/pnpm:$PATH"
            pnpm i --frozen-lockfile
            pnpm build
            pnpm prune --prod
            pm2 reload all
